name: Test Terraform
on:
  workflow_dispatch:

jobs:
  test-terraform:
    runs-on: ubuntu-latest
    environment: aws
    env:
      DUPLO_TOKEN: ${{ secrets.DUPLO_TOKEN }}
      DUPLO_HOST: ${{ secrets.DUPLO_HOST }}
      DUPLO_TENANT: ${{ secrets.DUPLO_TENANT }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node24
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Duplo Setup AWS
        uses: mkuntaDuplo/actions@node24-test
        with:
          admin: true

      - name: Terraform Setup
        uses: mkuntaDuplo/actions/setup-terraform@node24-test

      - name: Verify Terraform
        run: terraform version

      - name: Verify Node24
        run: node --version
