name: Test AWS
on:
  workflow_dispatch:

jobs:
  test-aws:
    runs-on: ubuntu-latest
    environment: aws
    env:
      DUPLO_TOKEN: ${{ secrets.DUPLO_TOKEN }}
      DUPLO_HOST: ${{ secrets.DUPLO_HOST }}
      DUPLO_TENANT: ${{ secrets.DUPLO_TENANT }}
    steps:
      - name: Setup Node24
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          region: us-east-1

      - name: Verify AWS
        run: aws sts get-caller-identity
