name: Test Azure
on:
  workflow_dispatch:

jobs:
  test-azure:
    runs-on: ubuntu-latest
    environment: azure
    env:
      DUPLO_TOKEN: ${{ secrets.DUPLO_TOKEN }}
      DUPLO_HOST: ${{ secrets.DUPLO_HOST }}
      DUPLO_TENANT: ${{ secrets.DUPLO_TENANT }}
    steps:
      - name: Duplo Setup Azure
        uses: mkuntaDuplo/actions@node24-test
        with:
          credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Verify Azure
        run: az account show

      - name: Verify Node24
        run: node --version
